### ISSUE TITLE
Se aqui tivesse um else, para dar uma fresh na tela?

### ISSUE THREAD

**Issue by ViniciusDeep** [jonh1036/Snake-Game#3]
https://github.com/jonh1036/Snake-Game/blob/1deef5df4db7b068a2eebc205b2f12b93a9a7dfd/snake.c#L62

**Comment by jonh1036** [comment]
Seria uma boa

**Comment by jonh1036** [comment]
Mas tem que implementar a condição

**Comment by ViniciusDeep** [comment]
Problem solved by jonh1036
